// <auto-generated />
namespace DatabaseManager.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class PricesV01 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PricesV01));
        
        string IMigrationMetadata.Id
        {
            get { return "201609040914299_PricesV01"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
